import { inspectChatZip } from './parsers/zip-import.js';
import { inspectChatFile } from './integration/direct-import.js';
import { requestObserverLocation, createObserverLocation } from './location/location-engine.js';
import { initGlobe, renderGlobeObservations } from './terrain/globe-view.js';
import { ingestExport } from './data/evidence-store.js';
import { buildObservations } from './data/observation-builder.js';
import { buildEntityTimeline, summarizeConditionHistory } from './temporal/entity-history.js';
import { createInteractionIndex, getObservationContext } from './ui/evidence-linker.js';
import { renderEvidencePanel } from './ui/evidence-panel.js';
import { inspectMedia, classifyLocationEvidence, createMediaPreviewUrl } from './media/evidence-inspector.js';
import { createObjectLocationCandidate, confirmObjectLocation, rejectObjectLocation } from './data/object-location.js';
import { createConditionAssessment, summarizeConditionAssessments } from './data/condition-assessment.js';
import { loadAppState, saveAppState } from './integration/app-persistence.js';

const demo={observers:[{id:'u1',name:'Ramesh',lat:30.0869,lng:78.2676,accuracy:12,time:'2026-08-30 08:42'},{id:'u2',name:'Sita',lat:30.0892,lng:78.2741,accuracy:18,time:'2026-08-30 09:10'}],observations:[{id:'W-001',type:'Waste dumping',lat:30.0881,lng:78.2714,accuracy:35,confidence:'High',time:'2026-08-30 08:45',distance:'480 m',elevation:1120,slope:'18°',evidence:'2 images + 1 video',condition:'Poor'},{id:'W-002',type:'Roadside waste',lat:30.091,lng:78.278,accuracy:65,confidence:'Estimated',time:'2026-08-30 09:15',distance:'620 m',elevation:1095,slope:'11°',evidence:'1 image',condition:'Moderate'},{id:'W-003',type:'Water pollution',lat:30.084,lng:78.269,accuracy:25,confidence:'High',time:'2026-08-30 10:08',distance:'310 m',elevation:1105,slope:'7°',evidence:'1 image + 2 messages',condition:'Poor'}],messages:[1,2,3,4,5,6],media:[1,2,3,4],assessments:[]};
const map=L.map('map',{zoomControl:true}).setView([30.0875,78.272],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const observerLayer=L.layerGroup().addTo(map),objectLayer=L.layerGroup().addTo(map),candidateLayer=L.layerGroup().addTo(map);let globeReady=false,currentData=demo,allObservations=demo.observations||[],interactionIndex=createInteractionIndex(demo),selectedObservation=null,activeMediaUrl=null;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function icon(type='object'){const c=type==='observer'?'#2878c8':type==='estimated'?'#d6a52b':type==='candidate'?'#fff':'#d74c4c',b=type==='candidate'?'#1f6f52':'white';return L.divIcon({className:'custom-marker',html:`<div style="width:17px;height:17px;border-radius:50%;background:${c};border:3px solid ${b};box-shadow:0 1px 5px #555"></div>`,iconSize:[17,17],iconAnchor:[8,8]})}
function clearMap(){observerLayer.clearLayers();objectLayer.clearLayers();candidateLayer.clearLayers()}
function fit(){const layers=[...observerLayer.getLayers(),...objectLayer.getLayers()];if(layers.length)map.fitBounds(L.featureGroup(layers).getBounds().pad(.18))}
function timeValue(o){const d=new Date(o?.time||o?.timestamp||o?.dateTime||o?.date||'');return Number.isNaN(d.getTime())?null:d.getTime()}
function filteredObservations(){const valid=allObservations.filter(o=>timeValue(o)!==null);if(!valid.length||Number($('timeRange').value)>=100)return allObservations;const min=Math.min(...valid.map(timeValue)),max=Math.max(...valid.map(timeValue)),cutoff=min+(max-min)*(Number($('timeRange').value)/100);return allObservations.filter(o=>{const t=timeValue(o);return t===null||t<=cutoff})}
function renderData(data,{persist=true}={}){currentData=data||{};allObservations=currentData.observations||[];interactionIndex=createInteractionIndex(currentData);clearMap();(currentData.observers||[]).forEach(u=>{const lat=Number(u.lat??u.latitude),lng=Number(u.lng??u.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;L.marker([lat,lng],{icon:icon('observer')}).bindPopup(`<strong>Observer</strong><br>${esc(u.name||'Observer')}<br>Accuracy: ±${u.accuracy??u.accuracy_m??'unknown'} m`).addTo(observerLayer)});filteredObservations().forEach(o=>{const lat=Number(o.lat??o.latitude),lng=Number(o.lng??o.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;L.marker([lat,lng],{icon:icon(o.confidence==='Estimated'?'estimated':'object')}).on('click',()=>selectObservation(o)).bindPopup(`<strong>${esc(o.type||'Observation')}</strong><br>${esc(o.time||o.timestamp||'')}<br>Accuracy: ±${o.accuracy??o.accuracy_m??'unknown'} m`).addTo(objectLayer)});$('observerCount').textContent=(currentData.observers||[]).length;$('obsCount').textContent=filteredObservations().length;$('messageCount').textContent=(currentData.messages||[]).length;$('mediaCount').textContent=(currentData.media||[]).length;window.chatMaplyObservations=filteredObservations();fit();if(globeReady)renderGlobeObservations(window.chatMaplyObservations);if(persist)persistState()}
async function persistState(){try{await saveAppState({version:1,saved_at:new Date().toISOString(),data:currentData})}catch(err){console.warn('ChatMaply state was not persisted:',err)}}
function selectedAssessments(){return(currentData.assessments||[]).filter(a=>a.observation_id===selectedObservation?.id)}
function renderAssessmentStatus(){const s=summarizeConditionAssessments(selectedAssessments());$('conditionStatus').textContent=selectedObservation?(s.count?`Latest: ${s.latest} • Trend: ${s.trend}`:`No assessment yet for ${selectedObservation.id}.`):'Select a mapped report first.';$('saveCondition').disabled=!selectedObservation}
function selectObservation(o){selectedObservation=o;const s=summarizeConditionAssessments(selectedAssessments());$('observationCard').innerHTML=`<h3>Selected report</h3><div class="obs-title">${esc(o.type||'Observation')}</div><p><strong>${esc(o.id)}</strong> • ${esc(o.time||o.timestamp||'Time unknown')}</p><p>📍 ${Number(o.lat??o.latitude).toFixed(5)}, ${Number(o.lng??o.longitude).toFixed(5)}</p><p>📏 Location accuracy: ±${o.accuracy??o.accuracy_m??'unknown'} m</p><p>⛰️ Elevation: ${esc(o.elevation??o.terrain?.elevation_m??'Not available')} • Slope: ${esc(o.slope??o.terrain?.slope??'Not available')}</p><p>↔ Distance from observer: ${esc(o.distance||'Not available')}</p><p>Evidence: ${esc(o.evidence||'Chat report')}</p><div class="chips"><span class="chip">${esc(o.confidence||'Unverified')}</span><span class="chip">${o.location_status==='confirmed'?'Object location confirmed':'Object / event'}</span>${s.count?`<span class="chip">Condition: ${esc(s.latest)}</span>`:''}</div><div class="confirm-actions"><button class="primary small" id="confirmObject">✓ Confirm object location</button><button class="secondary small" id="moveObject">Move marker</button><button class="text-button" id="rejectObject">Reject</button></div>`;$('confirmObject').onclick=confirmSelectedObject;$('moveObject').onclick=()=>moveObject(o);$('rejectObject').onclick=rejectSelectedObject;const context=getObservationContext(o.id,interactionIndex);const timeline=buildEntityTimeline({entity_id:context?.entity_id||o.entity_id,evidence_ids:[o.id]},currentData.observations||[],currentData.lineages||[]);const hs=summarizeConditionHistory(timeline);$('timelineCard').innerHTML=`<h3>Place history</h3><p>First: <strong>${esc(hs.first_condition)}</strong> · Latest: <strong>${esc(hs.latest_condition)}</strong> · Trend: <strong>${esc(hs.trend)}</strong></p>${timeline.map(e=>`<p>🕒 ${esc(e.timestamp||'Time unknown')} · ${esc(e.condition)}</p>`).join('')||'<p class="muted">No verified history available.</p>'}`;renderEvidencePanel($('evidencePanel'),context);renderAssessmentStatus()}
function candidate(o){return createObjectLocationCandidate({observationId:o.id,latitude:o.lat??o.latitude,longitude:o.lng??o.longitude,accuracy_m:o.accuracy??o.accuracy_m,source:o.source||'mapped-observation',confidence:o.confidence||'Unverified',timestamp:o.time||o.timestamp||null})}
function confirmSelectedObject(){if(!selectedObservation)return;selectedObservation.object_location=confirmObjectLocation(candidate(selectedObservation),{note:'Confirmed during map review.'});selectedObservation.location_type='OBJECT_LOCATION';selectedObservation.location_status='confirmed';renderData(currentData);selectObservation(selectedObservation);$('statusText').textContent=`${selectedObservation.id}: object location confirmed. Observer location remains separate.`}
function rejectSelectedObject(){if(!selectedObservation)return;selectedObservation.object_location=rejectObjectLocation(candidate(selectedObservation),{note:'Rejected during map review.'});selectedObservation.location_status='rejected';persistState();$('statusText').textContent=`${selectedObservation.id}: location rejected.`;selectObservation(selectedObservation)}
function moveObject(o){$('statusText').textContent='Click the map where the object/event is actually located.';map.once('click',e=>{const c=createObjectLocationCandidate({observationId:o.id,latitude:e.latlng.lat,longitude:e.latlng.lng,accuracy_m:o.accuracy??o.accuracy_m,source:'manual-map',confidence:'User placed',timestamp:o.time||o.timestamp||null});candidateLayer.clearLayers();L.marker([c.latitude,c.longitude],{icon:icon('candidate')}).addTo(candidateLayer).bindPopup('Candidate object location').openPopup();o.object_location=confirmObjectLocation(c,{note:'Placed and confirmed by map reviewer.'});o.lat=o.object_location.latitude;o.lng=o.object_location.longitude;o.latitude=o.lat;o.longitude=o.lng;o.location_type='OBJECT_LOCATION';o.location_status='confirmed';renderData(currentData);selectObservation(o);$('statusText').textContent=`${o.id}: new object location confirmed.`})}
async function processFile(file){$('processBtn').disabled=true;$('processBtn').textContent='Processing…';try{const result=file.name.toLowerCase().endsWith('.zip')?await inspectChatZip(file):await inspectChatFile(file);const observations=buildObservations(result);const data=ingestExport({...result,observations,assessments:[]});renderData(data);$('statusText').textContent=`Imported ${data.messages.length} messages and ${data.media.length} media files; ${data.observations.length} evidence locations mapped. No locations were invented.`;$('importHelp').textContent=`Parser: ${result.parser||'unknown'} • Status: ${result.parser_status||'unknown'} • Location mapping is evidence-only.`;$('processBtn').textContent='Processed'}catch(e){console.error(e);$('statusText').textContent=`Could not process this export: ${e.message}`;$('processBtn').textContent='Try again'}finally{$('processBtn').disabled=false}}
renderData(demo,{persist:false});
$('fitMap').onclick=fit;
$('toggleGlobe').onclick=async()=>{const globe=$('globe'),mapEl=$('map');if(!globe.hidden){globe.hidden=true;mapEl.hidden=false;$('toggleGlobe').textContent='3D Globe';map.invalidateSize();return}globe.hidden=false;mapEl.hidden=true;$('toggleGlobe').textContent='2D Map';if(!globeReady){await initGlobe('globe');globeReady=true}renderGlobeObservations(window.chatMaplyObservations||[])};
$('shareLocation').onclick=()=>{const s=$('locationStatus');s.textContent='Requesting location permission…';requestObserverLocation(location=>{const o=createObserverLocation({userId:'current-user',groupId:'current-group',location});const lat=o.latitude??o.lat,lng=o.longitude??o.lng;if(Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))){o.lat=Number(lat);o.lng=Number(lng);currentData.observers=[...(currentData.observers||[]),o];renderData(currentData);map.setView([o.lat,o.lng],Math.max(map.getZoom(),15))}s.textContent=`Location shared • ±${o.accuracy_m??o.accuracy??'unknown'} m accuracy`},e=>{s.textContent=e.code===1?'Location permission was not granted.':`Location unavailable: ${e.message}`})};
let selectedFile=null;$('chatFile').onchange=e=>selectFile(e.target.files?.[0]);$('dropzone').ondragover=e=>e.preventDefault();$('dropzone').ondrop=e=>{e.preventDefault();selectFile(e.dataTransfer.files?.[0])};function selectFile(f){selectedFile=f||null;$('fileRow').hidden=!selectedFile;$('processBtn').disabled=!selectedFile;if(selectedFile)$('fileName').textContent=`${selectedFile.name} (${Math.max(1,Math.round(selectedFile.size/1024))} KB)`}$('clearFile').onclick=()=>{$('chatFile').value='';selectFile(null)};$('processBtn').onclick=()=>selectedFile&&processFile(selectedFile);
$('timeRange').oninput=()=>{const v=$('timeRange').value;$('timeValue').textContent=v==='100'?'All':`${v}% of time range`;renderData(currentData)};
$('mediaFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const box=$('mediaResult');box.innerHTML='<p>Inspecting media locally…</p>';try{if(activeMediaUrl)URL.revokeObjectURL(activeMediaUrl);activeMediaUrl=createMediaPreviewUrl(file);const info=await inspectMedia(file),c=classifyLocationEvidence({exif:info.exif});const preview=info.media_type==='video'?`<video controls src="${activeMediaUrl}" aria-label="Selected video"></video>`:`<img src="${activeMediaUrl}" alt="Selected image preview">`;box.innerHTML=`<div class="media-grid"><div>${preview}</div><div><span class="evidence-badge">${esc(c.type)}</span><p><strong>${esc(file.name)}</strong></p><p>Type: ${esc(info.media_type)}</p><p>Size: ${Math.round(info.size_bytes/1024)} KB</p><p>Location: ${info.location?`${Number(info.location.latitude).toFixed(6)}, ${Number(info.location.longitude).toFixed(6)}`:'Not available'}</p><p>${esc(c.note)}</p><p class="muted">${esc(info.location_status)}</p></div></div>`}catch(e){box.innerHTML=`<p class="muted">Could not inspect this file: ${esc(e.message)}</p>`}};
$('saveCondition').onclick=()=>{if(!selectedObservation)return;const a=createConditionAssessment({observationId:selectedObservation.id,objectType:$('conditionObjectType').value,condition:$('conditionLevel').value,quantity:$('conditionQuantity').value.trim()||null,obstruction:$('conditionObstruction').value,contamination:$('conditionContamination').value,notes:$('conditionNotes').value.trim(),confidence:'Human reviewed'});currentData.assessments=[...(currentData.assessments||[]),a];selectedObservation.condition=a.condition;renderData(currentData);selectObservation(selectedObservation);$('conditionNotes').value='';$('conditionQuantity').value='';$('conditionStatus').textContent=`Assessment saved for ${selectedObservation.id}: ${a.condition}.`};
loadAppState().then(saved=>{if(saved?.data?.observations){renderData(saved.data,{persist:false});$('statusText').textContent=`Restored saved ChatMaply dataset from ${new Date(saved.saved_at).toLocaleString()}.`}}).catch(err=>console.warn('Restore skipped:',err));
