// BUILD-29: Signal-compatible adapter for recognizable user-supplied exports.
// Signal has no single universal portable chat-export format across clients.
// This adapter parses only explicit JSON/TXT structures and never invents data.
import { normalizeMessage } from './common.js';
function safeDate(value){if(value===undefined||value===null||value==='')return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString();}
function normalizeSignalRecord(record,index){if(!record||typeof record!=='object')return null;const text=String(record.text??record.body??record.message??'');const sender=String(record.sender??record.author??record.from??'Unknown');const timestamp=safeDate(record.timestamp??record.time??record.date??record.created_at??record.createdAt);return normalizeMessage({id:String(record.id??`signal-${index+1}`),sender,date:timestamp?timestamp.slice(0,10):null,time:timestamp?timestamp.slice(11,19):null,text,media:record.media??null});}
export function parseSignalJSON(input){let data;try{data=typeof input==='string'?JSON.parse(input):input;}catch{const e=new Error('Signal JSON is invalid.');e.code='INVALID_JSON';throw e;}const records=Array.isArray(data)?data:(Array.isArray(data.messages)?data.messages:Array.isArray(data.chats)?data.chats:[]);return records.map(normalizeSignalRecord).filter(Boolean);}
export function parseSignalText(text=''){const out=[];const patterns=[/^(\d{1,4}[-/.]\d{1,2}[-/.]\d{1,4})[ ,]+(\d{1,2}:\d{2}(?::\d{2})?)[ -]+([^:]+):\s?(.*)$/,/^\[([^\]]+)\]\s*([^:]+):\s?(.*)$/];String(text).split(/\r?\n/).forEach((line,index)=>{for(const p of patterns){const m=line.match(p);if(!m)continue;if(p===patterns[0])out.push(normalizeMessage({id:`signal-${index+1}`,sender:m[3].trim(),date:m[1],time:m[2],text:m[4],media:null}));else{const d=new Date(m[1]);out.push(normalizeMessage({id:`signal-${index+1}`,sender:m[2].trim(),date:Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10),time:Number.isNaN(d.getTime())?null:d.toISOString().slice(11,19),text:m[3],media:null}));}break;}});return out;}
export function detectSignalExport({name='',text=''}={}){const lower=String(name).toLowerCase();const t=String(text).trim();if(lower.includes('signal')&&(lower.endsWith('.json')||lower.endsWith('.txt')))return lower.endsWith('.json')?'signal-json':'signal-text';if(t.startsWith('{')||t.startsWith('[')){try{const d=JSON.parse(t);if(d&&(Array.isArray(d.messages)||Array.isArray(d.chats)))return 'signal-json';}catch{}}return null;}
