// BUILD-31: end-to-end ZIP import router. Platform adapters remain conservative.
import { classifyMedia } from './common.js';
import { parseWhatsApp } from './whatsapp.js';
import { parseTelegramExport } from './telegram.js';
import { parseSignalJSON, parseSignalText, detectSignalExport } from './signal.js';
import { parseMessengerJSON, detectMessengerExport } from './messenger.js';
const lowerName=n=>String(n||'').toLowerCase();
function mediaFiles(entries){return entries.map(e=>({path:e.name,name:e.name.split('/').pop(),mediaType:classifyMedia(e.name),size:e._data?.uncompressedSize||0}));}
export async function inspectChatZip(file){if(!file)throw new Error('No ZIP file selected.');if(!window.JSZip)throw new Error('ZIP library is not loaded.');const zip=await window.JSZip.loadAsync(file);const entries=Object.values(zip.files).filter(e=>!e.dir);const files=mediaFiles(entries);const candidates=entries.filter(e=>/\.(txt|json)$/i.test(e.name));let messages=[],parser='none',parser_status='NO_CHAT_DATA',chat_file=null;for(const e of candidates){const name=e.name.split('/').pop(),text=await e.async('text'),n=lowerName(name);try{if(n==='chat.txt'||n==='_chat.txt'||n.includes('whatsapp')){messages=parseWhatsApp(text);parser='whatsapp-txt';chat_file=e.name;break;}const signal=detectSignalExport({name,text});if(signal==='signal-json'){messages=parseSignalJSON(text);parser='signal-json';chat_file=e.name;break;}if(signal==='signal-text'){messages=parseSignalText(text);parser='signal-text';chat_file=e.name;break;}const messenger=detectMessengerExport({name,text});if(messenger==='messenger-json'){messages=parseMessengerJSON(text);parser='messenger-json';chat_file=e.name;break;}if(n.endsWith('.json')&&/result|chat|export|telegram/.test(n)){messages=parseTelegramExport(text);parser='telegram-json';chat_file=e.name;break;}}catch(err){parser_status=err.code==='INVALID_JSON'?'INVALID_JSON':'PARSER_ERROR';chat_file=e.name;break;}}if(parser_status==='NO_CHAT_DATA')parser_status=messages.length?'PARSED':'NO_MESSAGES_MATCHED';const media=files.filter(f=>f.mediaType==='image'||f.mediaType==='video');return{fileName:file.name,totalFiles:files.length,media,images:media.filter(f=>f.mediaType==='image'),videos:media.filter(f=>f.mediaType==='video'),messages,files,parser,parser_status,chat_file,qa:{archive_readable:true,message_count:messages.length,media_count:media.length,unsupported_files:files.filter(f=>f.mediaType==='other').length}};}
